services:
  - type: web
    name: cinepolito-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cinepolito-db
          property: connectionString
          
databases:
  - name: cinepolito-db
    databaseName: cinepolito
    user: admin
